enum ActionTypes {
  GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST",
  GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS",
  GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE",

  GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST",
  GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS",
  GET_MOVIE_FAILURE = "GET_MOVIE_FAILURE",
}

export default ActionTypes
